# Generated by Django 5.1.1 on 2024-09-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_contacts_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
